### ISSUE TITLE
Consistent versioning between assembly and nuget in yaml pipeline

### ISSUE THREAD

**Issue by ptr727** [BMuuN/vsts-assemblyinfo-task#120]
I am trying to use consistent naming between manifest and nuget package version numbers, but Azure and Yaml pipelines makes this difficult or impossible.

The commonly used versioning variables are only available in the name, they are not generally available for use as parameters.
```
name: $(MajorVersion).$(MinorVersion).$(Date:yyyyMMdd).$(Rev:r)
```
`name` converts into the `$(Build.BuildNumber)` variable.

Manifest versioning cannot use the above format because the date field results in a too big number.
If I use `$(DayOfYear)`, it is prefixed with a 0, and again can't be used in the manifest.
We have to use the wildcard versioning.
```
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: Version
  inputs:
    VersionNumber: $(MajorVersion).$(MinorVersion).0.0
    FileVersionNumber: $(MajorVersion).$(MinorVersion).*.*
    InformationalVersion: $(MajorVersion).$(MinorVersion).*.*
    PackageVersion: $(MajorVersion).$(MinorVersion).*.*
```

The `DotNetCoreCLI@2` task can use the build number or a variable for versioning.
But now there is no way to get a manifest version and a nuget package version to match.
```
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: byBuildNumber
```

How do I get auto incrementing, manifest and nuget compliant version numbers, that use the same version between the manifest and the nuget package?

**Comment by ptr727** [comment]
I got a reasonably working solution using the GitVersion tool.
I used a combination of GitVersion and Assembly-Info-NetCore to dynamically create a gitflow version number, and then set it in the vcproj manifest.
The only remaining problem is that rebuilds without a git commit will create duplicate nuget package versions.

E.g.
```
# Calculate the GitFlow version numbers
# https://gitversion.net/docs/build-server-support/build-server/azure-devops
- task: GitVersion@5
  displayName: 'Run GitVersion Tool'
  inputs:
    runtime: core
    configFilePath: gitversion.yml

# Set the manifest versions
# Modify the csproj file directly and use values valculated but GitVersion tool
# https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Attributes
- task: Assembly-Info-NetCore@2
  displayName: 'Set Version Information'
  inputs:
    FileNames: 'Utilities/Utilities.csproj'
    VersionNumber: $(GitVersion.AssemblySemVer)
    FileVersionNumber: $(GitVersion.AssemblySemFileVer)
    InformationalVersion: $(GitVersion.InformationalVersion)
    PackageVersion: $(GitVersion.InformationalVersion)
    LogLevel: verbose
```
