### ISSUE TITLE
Commented line in AssemblyInfo.cs source will be changed but is still commented

### ISSUE THREAD

**Issue by VeldMuijz** [BMuuN/vsts-assemblyinfo-task#131]
Hi there,
Was using this plugin and had some issues setting the properties in the AssemblyInfo.cs file.
What I experienced was that when you have a line commented out, and changed it with this plugin, the values will be changed but the line will not be uncommented.

E.g.:
Source file:
`//[assembly: AssemblyFileVersion("1.1.0.0")]`

Run plugin with instruction to change it:
```
- task: Assembly-Info-NetFramework@2
           inputs:
              Path: '$(Build.SourcesDirectory)src\Properties\'
              FileNames: 'AssemblyInfo.cs'
              InsertAttributes: true
              VersionNumber: 1.1.0.$(Build.BuildId)
              FileVersionNumber: 1.1.0.$(Build.BuildId) 
              LogLevel: verbose
              FailOnWarning: false
              DisableTelemetry: true
```
Result:
`//[assembly: AssemblyFileVersion("1.1.0.12324")]`

I would expect this plugin to insert a new line with the AssemblyVersion set from the pipeline task.
