### ISSUE TITLE
Getting error on version number when writing to csproj file while publishing web artifact in Azure DevOps build.

### ISSUE THREAD

**Issue by JGSilverman** [BMuuN/vsts-assemblyinfo-task#171]
I have the following task in my Azure build yml definition. We're using Blazor Server

```
- task: Assembly-Info-NetCore@2
  displayName: "Write version number to csproj"
  condition:  succeeded()
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: true
    Company: 'My Company'
    Product: 'My project'
    VersionNumber: '$(Build.BuildNumber)'
    PackageVersion: '$(versionNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

```

`$(versionNumber)` is a string value.

I'm receiving the following error on this task:

```
- task: DotNetCoreCLI@2
  displayName: "Publish Web Artifact"
  inputs:
    command: 'publish'
    projects: '**/MyProject.Web.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: true
```

 error : '1.0.0317.20210317.19' is not a valid version string.
Error: The process 'D:\_agent2\_work\_tool\dotnet\dotnet.exe' failed with exit code 1
Dotnet command failed with non-zero exit code on the following projects : D:\_agent2\_work\2\s\MyProject\Web\MyProject.Web.csproj
