### ISSUE TITLE
NuGet Package Is Not Generated Even If Flag is Enabled

### ISSUE THREAD

**Issue by Axemasta** [BMuuN/vsts-assemblyinfo-task#178]
I was using the `DotNetCoreCLI@2` tool to pack my NuGet up and then push it to an Azure DevOps feed. I got everything working and swapped to use this task to handle versioning. My pipeline was working until the switch, here was the YAML:
```
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000'
```

When I swapped to use `Assembly-Info-NetCore@2` I had the following YAML:
```
- task: Assembly-Info-NetCore@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: $(versionNumber)
    FileVersionNumber: $(assemblyVersion)
    PackageVersion: $(versionNumber)
    LogLevel: 'verbose'
    GeneratePackageOnBuild: true
    FailOnWarning: false
    DisableTelemetry: false

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000'
```

I was noticing the following warning on the push command:
```
##[warning]No packages matched the search pattern.
```

If you look at the output of the `Assembly-Info-NetCore@2` task:
```
Generate NuGet package on build: true
```

My class librarys csproj looks like this:
```
<Project Sdk="MSBuild.Sdk.Extras/3.0.23">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;netstandard2.1;net471;net472;net48</TargetFrameworks>
	<Configurations>Debug;Release</Configurations>
  </PropertyGroup>

</Project>
```

Upon explicitly adding:
`<GeneratePackageOnBuild Condition=" '$(Configuration)'=='RELEASE' ">True</GeneratePackageOnBuild>`

The package was picked up by the push command which leads me to believe it never got created when I built the project, which I am doing with:
```
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) -p:Version=$(assemblyVersion)'
    projects: '**/*.csproj'
```

Have I just set this up wrong or is the flag from the `Assembly-Info-NetCore@2` task not being picked up during the build. I'm happy to share logs etc. My package is currently building and being pushed with the correct version info so things are working!
