### ISSUE TITLE
Invalid date output in "Informational version"

### ISSUE THREAD

**Issue by mikeKuester** [BMuuN/vsts-assemblyinfo-task#183]
Hello,

I tried the Assembly Info Task and run into a bug? (or is that a misconfiguration from me?)

The revision number should contain the year and the day of the year. Therefore I use the following string: `$(date:YYDDD DDDD)`, which works perfect for the _version_ and the _version file number_, but not for the _informal version_. It added the date of the year twice:

Informational version: 1.1.296.21307 **_307_**

I would expect to get the same output in all three cases.

```
--- CONFIG ---

- task: Assembly-Info-NetCore@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    GeneratePackageOnBuild: false
    Company: 'ACME'
    Product: 'product a'
    Copyright: 'Copyright © ACME $(date:YYYY)'
    VersionNumber: '1.1.$(Build.BuildId).$(date:YYDDD DDDD)'
    FileVersionNumber: '1.1.$(Build.BuildId).$(date:YYDDD DDDD)'
    InformationalVersion: '1.1.$(Build.BuildId).$(date:YYDDD DDDD)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false
```

```
--- LOG ---

==============================================================================
Task         : Assembly Info (.Net Core & .Net Standard)
Description  : Set assembly or package information such as Version, Copyright and Repository URL's etc.
Version      : 2.3.105
Author       : Bleddyn Richards
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)
==============================================================================
Task Parameters...
Source folder: D:\a\1\s
Source files: **/*.csproj
Insert attributes: true
File encoding: auto
Write unicode BOM: false
Generate NuGet package on build: false
Require license acceptance: false
Package id: 
Package version: 
Authors: 
Company: ACME
Product: product a
Description: 
Copyright: Copyright © ACME 2021
License Url: 
Project Url: 
Icon Url: 
Repository Url: 
Repository type: 
Tags: 
Release notes: 
Assembly neutral language: 
Assembly version: 1.1.296.21307
Assembly file version: 1.1.296.21307
Informational version: 1.1.296.21307 307  <======= wrong!
Log Level: verbose
Fail on Warning: false

Setting .Net Core / .Net Standard assembly info...
Processing: D:\a\1\s\source\product a\AppHost.Tests\AppHost.Tests.csproj
Detected file encoding: utf-8
GeneratePackageOnBuild --> false
PackageRequireLicenseAcceptance --> false
Company --> ACME
Product --> product a
Copyright --> Copyright © ACME 2021
AssemblyVersion --> 1.1.296.21307
FileVersion --> 1.1.296.21307
InformationalVersion --> 1.1.296.21307 307  <======= wrong!
Verify file encoding: iso-8859-2

```

Thanks for your work!

Ciao,
Mike
