### ISSUE TITLE
The task just ignores complex expressions

### ISSUE THREAD

**Issue by samusaran** [BMuuN/vsts-assemblyinfo-task#187]
```
- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs
      **\AssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(Date:yyyy).$(Date:MM).$(Date:dd)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false
```

I'm trying to set the version based on dates, but the task ignores the VersionNumber attribute and it passes over it:
```
Setting .Net Framework assembly info...
Processing: D:\a\1\s\ProjectName\Properties\AssemblyInfo.cs
Detected file encoding: utf-8
Adding --> using System.Runtime.CompilerServices;
AssemblyConfiguration --> Release
Verify file encoding: iso-8859-1
```

If I use $(Build.BuildNumber) it works but the build number has an invalid format so it's not doable.
