### ISSUE TITLE
task: Assembly-Info-NetCore@3 not recognized 

### ISSUE THREAD

**Issue by Martin-Andersen** [BMuuN/vsts-assemblyinfo-task#222]
How can I install/use the extension in my azure-pipelines.yaml file?

Have inserted this. And the task are not recognized

```
  - task: Assembly-Info-NetCore@3
            displayName: 'Set Assembly Metadata'
            inputs:
              Path: '$(Build.SourcesDirectory)'
              FileNames: '**/*.csproj'
              InsertAttributes: true
              FileEncoding: 'utf-8'
              WriteBOM: true
              FailOnWarning: true
              Authors: 'Bleddyn Richards'
              Company: 'Example Ltd'
              Copyright: 'Copyright © $(date:YYYY) Example Ltd'
              PackageVersion: '$(appVersion)'
              UpdateBuildNumber: '$(Build.DefinitionName)_v$(appVersion)'
              AddBuildTag: 'v$(appVersion)'

```
