### ISSUE TITLE
Issue with .NET 5

### ISSUE THREAD

**Issue by msganti** [BMuuN/vsts-assemblyinfo-task#238]
I am facing an issue with a .NET 5 project. Here are some details:

In the Build YAML:
![image](https://user-images.githubusercontent.com/7071408/158202458-c878491d-82c8-43ab-aae8-ee26ca8e6530.png)

Source Project:
![image](https://user-images.githubusercontent.com/7071408/158202741-0ce4eb9e-68c1-4011-9d95-460972be5c6a.png)

Build Pipeline Output:
![image](https://user-images.githubusercontent.com/7071408/158202944-60d81ed6-502c-4763-b02e-521c6d557150.png)

**Comment by BMuuN** [comment]
Try changing your yaml to ensure the value is referencing the variable `$()`:

```yaml
VersionNumber: '$(buildnumber)'
FileVersion: '$(buildnumber)'
AssemblyVersion: '$(buildnumber)'
```

and make sure you have the variable `buildnumber` defined in your yaml:

```yaml
variables:
  buildnumber: '1.0.0'
```
