### ISSUE TITLE
Version 3.2.1 has stopped working

### ISSUE THREAD

**Issue by PatrizioG** [BMuuN/vsts-assemblyinfo-task#269]
Hi
Version 3.2.1 has stopped working.
Hi, I have a DevOps pipeline with more or less 700 project (and also 700 AssemblyInfo.cs).
The task works successfully and replaces the first 60 files, subsequently stops replacing the variables AssemblyFileVersion and AssemblyVersion (the only ones with a variable substitution within them).
There doesn't seem to be an encoding problem. Even deleting that project the task behaves abnormally.
  
An extract of the log at the point where the anomaly begins
`Processing: C:\DEVOPS_BUILD\8\s\Injection\DataPicker\Standard.Customer.DPK.Tests\Properties\AssemblyInfo.cs
Detected file encoding: utf-16le
AssemblyVersion --> 1.4.11.142
AssemblyFileVersion --> 1.4.11.142
AssemblyCompany --> xxx
AssemblyConfiguration --> Release
AssemblyCopyright --> Copyright © xxx 2022
Verify file encoding: iso-8859-1
Processing: C:\DEVOPS_BUILD\8\s\Injection\DataPicker\Standard.Customer.DPKTests\Properties\AssemblyInfo.cs
Detected file encoding: utf-8
AssemblyCompany --> xxx
AssemblyConfiguration --> Release
AssemblyCopyright --> Copyright © xxx 2022
Verify file encoding: iso-8859-1
`

**Comment by BMuuN** [comment]
Hey @PatrizioG can you confirm if the task has previously worked for you and if you've updated from v2 to v3 this morning?

I'm not sure what you mean by it's worked for the first 60 files but failed on files that require substitution.  Can you check you have the correct tasks in your pipeline for the correct projects e.g. ".Net Framework" task to target `AssemblyInfo.cs` files and the ".Net Core & .Net Standard" task to target `*.csproj` files.

Have you tried forcing the encoding to `uft-8` and enabling `Write unicode BOM` ?

**Comment by kinjiru** [comment]
After working splendidly since April we've experienced a similar issue this week with file versions only being set on a few files after 3.2.1 release.
Based on the comment above about 60 files we made the FileNames globbing more restrictive (we were including AssemblyInfo files in repository not related to the solution being built) which reduced the number of AssemblyInfo files from more than 60 to to 15. This change alone resulted in file versions being set again (didn't need to force encoding or unicode bom).

Our task definition was
```
task: Assembly-Info-NetFramework@3.2.0
          displayName: 'Update AssemblyInfo'
          inputs:
            Path: '$(Build.SourcesDirectory)'
            FileNames: '**\AssemblyInfo.cs'
            InsertAttributes: false
            FileEncoding: 'auto'
            WriteBOM: false
            Title: 'XYZ'
            Product: 'XYZ'
            Description: 'XYZ'
            Company: 'XYZ'
            Copyright: 'XYZ'
            VersionNumber: '$(newVersionNumber)'
            FileVersionNumber: '$(newVersionNumber)'
            LogLevel: 'verbose'
            FailOnWarning: false
            AddBuildTag: '$(newVersionNumber)'
            DisableTelemetry: false
```

Hope this helps.
