### ISSUE TITLE
How to use the output variables in Azure Devops tasks?

### ISSUE THREAD

**Issue by jcawe** [BMuuN/vsts-assemblyinfo-task#286]
I use the step in the yaml of the Azure Devops but when I refer to variable `$(AssemblyInfo.Version)` it just not work and put the literal text instead of the value. Did I do something wrong?

```yaml
- task: Assembly-Info-NetFramework@3
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(MajorVersion).$(MinorVersion).*.*'
    FileVersionNumber: '$(MajorVersion).$(MinorVersion).*.*'
    InformationalVersion: '$(Build.BuildNumber)'
    AddBuildTag: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: true
    DisableTelemetry: true

[... some other tasks ...]

- task: PublishBuildArtifacts@1
  displayName: 'Publich artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'App_$(AssemblyInfo.Version)'
    publishLocation: 'Container'
```

In that example the artifact name is `App_$(AssemblyInfo.Version)` instead of 'App_1.0.6564.21234'

Why?

**Comment by BMuuN** [comment]
Hey @jcawe, in order to use output variables you will need to define a `name` for the task such as:

```yml
- task: Assembly-Info-NetFramework@3
  name: 'AI'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(MajorVersion).$(MinorVersion).*.*'
    FileVersionNumber: '$(MajorVersion).$(MinorVersion).*.*'
    InformationalVersion: '$(Build.BuildNumber)'
    AddBuildTag: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: true
    DisableTelemetry: true
```

you can then use the output variables in subsequent tasks as follows:

```yml
- task: PublishBuildArtifacts@1
  displayName: 'Publich artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'App_$(AI.AssemblyInfo.Version)'
    publishLocation: 'Container'
```
This is covered in Microsoft's [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-output-variables-from-tasks) but I'll update our Wiki using this example.
