### ISSUE TITLE
Tagging build (or final steps) takes 22 seconds

### ISSUE THREAD

**Issue by BryanAldrich** [BMuuN/vsts-assemblyinfo-task#356]
These are the logs from 3.3
2023-08-23T18:50:20.8201274Z $.AssemblyInfo.InformationalVersion: 4.0.1175.0
2023-08-23T18:50:20.8201559Z ##[endgroup]
2023-08-23T18:50:20.8201830Z ##[group]Updating build...
2023-08-23T18:50:20.8202084Z ##[endgroup]
2023-08-23T18:50:42.1352411Z ##[section]Finishing: Set Assembly Manifest Data

These are the logs from 3.2.2
2023-08-18T18:01:47.8919062Z $.AssemblyInfo.InformationalVersion: 4.0.1168.0
2023-08-18T18:01:47.8919347Z ##[endgroup]
2023-08-18T18:01:47.8919601Z Tagging build...
2023-08-18T18:02:09.4334992Z ##[section]Finishing: Set Assembly Manifest Data

I was able to get a diagnostic log from 3.3, but it is very similar.
2023-08-23T18:55:47.5114178Z ##[debug]##[endgroup]
2023-08-23T18:55:47.5114405Z ##[debug]task result: Succeeded
2023-08-23T18:55:47.5115255Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]Complete.
2023-08-23T18:56:08.8350757Z ##[section]Finishing: Set Assembly Manifest Data

The Build YAML
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
```
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-NetFramework@3
  displayName: 'Set Assembly Manifest Data'
  inputs:
    FileNames: |
     **/AssemblyInfo.cs
     !/FluentScheduler/**/AssemblyInfo.cs
     !/packages/**
    Title: 'Project X'
    Product: 'Project X - $(BuildConfiguration)'
    Company: 'Initrode'
    Copyright: 'Copyright © 2019'
    VersionNumber: '4.0.$(Build.BuildId).0'
    FileVersionNumber: '4.0.$(Build.BuildId).0'
    InformationalVersion: '4.0.$(Build.BuildId).0'
```
