### ISSUE TITLE
Build tag was not added successfully

### ISSUE THREAD

**Issue by furier** [BMuuN/vsts-assemblyinfo-task#363]
```yml
variables:
  - name: appVersion
    value: '#.#.*.*'

stages:
  - stage: build
    displayName: Build
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    variables:
      solutionPath: sln/path
    jobs:
      - job: build_solution
        displayName: Build, Test and Publish (Artifacts)
        steps:
          - checkout: self
            submodules: true
# other tasks...
          - task: Assembly-Info-NetCore@3
            displayName: 'Set Assembly Metadata'
            inputs:
              Path: '$(solutionPath)'
              FileNames: '**/*.csproj'
              InsertAttributes: true
              FileEncoding: 'iso-8859-2'
              WriteBOM: false
              PackageVersion: '$(appVersion)'
              LogLevel: 'verbose'
              FailOnWarning: true
              DisableTelemetry: true
#              UpdateBuildNumber: '$(Build.DefinitionName)_v$(appVersion)'
#              AddBuildTag: 'v$(appVersion)'
```

Causes the following error: `##[error]Build tag 'v#.#.8798.27461' was not added successfully.`

```sh
Starting: Set Assembly Metadata
==============================================================================
Task         : Assembly Info (.Net Core & .Net Standard)
Description  : Set assembly or package information such as Version, Copyright and Repository URL's etc.
Version      : 3.3.0
Author       : Bleddyn Richards
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)
==============================================================================
Task Parameters...
Setting .Net Core / .Net Standard assembly info...
Processing: D:\a\1\s\src\sln\path\project\Project.csproj
Setting output variables...
Updating build...
Async Command Start: Update Build Number
Update build number to Project_v#.#.8798.27461 for build 1409
Async Command End: Update Build Number
Async Command Start: Add Build Tag
Async Command End: Add Build Tag
##[error]Build tag 'v#.#.8798.27461' was not added successfully.
Finishing: Set Assembly Metadata
```
