### ISSUE TITLE
YAML configuration on DevOps Services

### ISSUE THREAD

**Issue by meriturva** [BMuuN/vsts-assemblyinfo-task#78]
I'm new to Azure Devops and i have correctly installed extensions on my free accounts.
Main problem is that i just have YAML editor so i really don't have any guide how to implement that task without visual step configuration on pipeline section.

Any help here?
So thanks.

**Comment by BMuuN** [comment]
I've not used the YAML editor therefore I'm not going to be a big help.  Having said that it is possible to design your build pipeline using the visual designer then view your pipeline in YAML.  I've just done this on one of my test builds and the task looks like this:
```
  - task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
    displayName: 'Set Assembly Manifest Data'
    inputs:
      FileNames: '**/*.csproj'
      InsertAttributes: true
      WriteBOM: true
      GeneratePackageOnBuild: true
      PackageId: 'vsts-assemblyinfo-task'
      Authors: 'Bleddyn Richards'
      Company: '$(Company)'
      Product: 'Azure DevOps Assembly Info'
      Description: 'Assembly Info is an extension for Team Services that sets assembly information from a build.'
      Copyright: 'Copyright © $(date:YYYY) $(date:DD.MM.YYYY DD MMMM YYYY HH:mm a) Example Ltd'
      PackageLicenseUrl: 'https://github.com/BMuuN/vsts-assemblyinfo-task/License.md'
      PackageProjectUrl: 'https://github.com/BMuuN/vsts-assemblyinfo-task/release'
      PackageIconUrl: 'https://github.com/BMuuN/vsts-assemblyinfo-task/favicon.png'
      RepositoryUrl: 'https://github.com/BMuuN/vsts-assemblyinfo-task'
      RepositoryType: 'OSS for Azure Dev Ops'
      PackageTags: 'Tags, Build, Release, VSTS'
      PackageReleaseNotes: 'The extension will recursively search the specified Source Folder for all files listed in the Source Files field and set the assembly data. This will result in assembly files containing common company or product information.'
      Culture: 'en-GB'
      VersionNumber: '$(Build.BuildNumber)'
      FileVersionNumber: '1990.03.*.*'
      InformationalVersion: '2.3.4-beta5'
      PackageVersion: '9.8.7-beta65'
```
